version: '3.9'
services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=password
volumes:
  dbdata:
