version: '3.9'
services:
  cache:
    image: redis:7.2.2-alpine
    container_name: redis722
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    restart: always
    volumes:
      - cache:/data
    ports:
      - '6379:6379'
volumes:
  cache:
    driver: local
